"""Some null changes

Revision ID: 58172a2ed7ce
Revises: 88405abb9d03
Create Date: 2020-12-09 20:04:33.811101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58172a2ed7ce'
down_revision = '88405abb9d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'employement_from_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'employement_from_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
