"""Initial migrations

Revision ID: 88405abb9d03
Revises: 
Create Date: 2020-12-09 19:00:42.540480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88405abb9d03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citizenhip', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('education_departmant', sa.String(length=100), nullable=True),
    sa.Column('education_date_entered', sa.Integer(), nullable=True),
    sa.Column('education_date_graduated', sa.Integer(), nullable=True),
    sa.Column('education_degree', sa.String(length=100), nullable=True),
    sa.Column('education_stream', sa.String(length=100), nullable=True),
    sa.Column('employement_organization_name', sa.String(length=100), nullable=True),
    sa.Column('employement_city', sa.String(length=100), nullable=True),
    sa.Column('employement_country', sa.String(length=100), nullable=True),
    sa.Column('employement_from_date', sa.DateTime(), nullable=False),
    sa.Column('employement_position', sa.String(length=100), nullable=True),
    sa.Column('employement_industry', sa.String(length=100), nullable=True),
    sa.Column('employement_sector', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
